### ISSUE TITLE
Feature Request: donut portfolio visualizer

### ISSUE THREAD

**Issue by chriskfwoo** [mani-coder/wealthica-portfolio-addon#17]
First off: Thanks for creating this addon :)

For the portfolio visualizer pie graph, I was wondering if it's possible to group the stocks by accounts?

For sample, 
If I have 3 accounts. In the outer layer...
- TD (50% of portfolio), Questrade (25% of portfolio), Wealthsimple Invest (25% of portfolio)

Then each layer will have an inner layer representing the stock percent allocation.

I see in your `package.json`, you are using highcharts.js, you think it's doable with donut chart? https://www.highcharts.com/demo/pie-donut

**Comment by mani-coder** [comment]
Thanks for the request, let me check it out!

**Comment by mani-coder** [comment]
Okay, I tried donut but it's bit clumsy with too many holdings and lengthy account names. So, I went ahead with the pie chart with drill down. Clicking on the account name will show the holdings chart.

![image](https://user-images.githubusercontent.com/11651746/113502424-1ffa9380-94e1-11eb-94be-38850849a7e6.png)

**Comment by chriskfwoo** [comment]
Hi, thanks for working on this :) Is it possible I can see a screenshot? IMO, I think having the holdings for each account is pretty important for this feature.

On Wealthica homepage, it already shows the % allocation for each account.

In this jsfiddle,

**Comment by mani-coder** [comment]
@chriskfwoo okies, I pushed out the donut chart, thanks! Yeah, 5% holding condition helped to clean up the chart and moved the inner chart label to far away so that they can be show'd clearly.

**Comment by chriskfwoo** [comment]
I see the update! Thanks a lot :) You can close this issue.

**Comment by mani-coder** [comment]
Welcome, glad it helps you.
