### ISSUE TITLE
Addon stopped working

### ISSUE THREAD

**Issue by strongwinderic** [mani-coder/wealthica-portfolio-addon#18]
It is not loading anymore. I have noticed it some some days ago.

I noticed some blocked requests when I opened inspect window:

![image](https://user-images.githubusercontent.com/9271579/114243370-0d091880-9952-11eb-9143-0517713f086d.png)

**Comment by mani-coder** [comment]
I haven't faced any issues with loading the add-on. 

Don't worry about the blocked requests, sometimes ad-blockers blocks some analytics requests. It should be fine.

Where there any other errors in the console? Can you let me know your browser, I will try to reproduce the issue using that?

**Comment by strongwinderic** [comment]
I runned it into an incognito window on latest chrome (stable). I am using wealthica new interface.  I have also turned off adblock. I do not see the request errors anymore. The page still does not load and there is the following error on console:

![image](https://user-images.githubusercontent.com/9271579/114446332-bd675e80-9b96-11eb-80ec-921c5e161ac4.png)

**Comment by strongwinderic** [comment]
Update: same error on old interface

**Comment by andrewmatheson** [comment]
Similar issue in firefox.

<img width="346" alt="Screen Shot 2021-04-13 at 12 37 47" src="https://user-images.githubusercontent.com/15182144/114580387-30cfa580-9c55-11eb-9d05-0843ccdd3389.png">

**Comment by mani-coder** [comment]
Oops, let me fix it and update shortly.

**Comment by mani-coder** [comment]
Deployed the fix for it, can you guys try now?

**Comment by andrewmatheson** [comment]
Fixed it for me. Thanks!

**Comment by strongwinderic** [comment]
It is working again, thank you so much!

**Comment by strongwinderic** [comment]
By the way, awesome new features. This addon is the best one we have there! It gives us great information!

**Comment by mani-coder** [comment]
thanks guys! Kudos to wealthica for allowing developers to write and publish their own :)
