### ISSUE TITLE
Selecting "All" for Timeline length doesn't work properly

### ISSUE THREAD

**Issue by mtbowler416** [mani-coder/wealthica-portfolio-addon#9]
Hi there - first of all, let me say this is an awesome addon! I've been using it for several months and it provides just what I want.

However, I did find one small issue - when I select "all" on any of the graphs for the timeline length, it only shows me from the beginning of the month 1 year ago. So for example today is April 17th 2020, selecting "all" shows from April 1st, 2019 to today. Once it is May, it will from May 1st, 2019 to current day etc. Not sure if this is a limitation of Wealthica itself or something that could be fixed.

Happy to help in any way I can (background in embedded systems, so this isn't exactly my wheelhouse).

**Comment by mani-coder** [comment]
Hi @mtbowler416, you need to adjust the dates in the main filter, by default it's one year only.

![image](https://user-images.githubusercontent.com/11651746/79827092-51229800-8352-11ea-9574-5f42e4d99230.png)
